#server:
  #port: 8761                    # 指定该Eureka实例的端口
#eureka:
  #instance:
    #hostname: peer1         # 指定该Eureka实例的主机名
  #client:
    #registerWithEureka: false
    #fetchRegistry: false
    #serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
spring:
  profiles: peer1                                 # 指定profile=peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1                               # 指定当profile=peer1时，主机名
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/      # 将自己注册到peer2这个Eureka上面去
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/