server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie-ribbon
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
  instance:
    preferIpAddress: true